#!/bin/bash
# Quick Setup Summary for EC2

echo "=============================================="
echo "  AWS Learning Platform - EC2 Setup"
echo "=============================================="
echo ""
echo "📋 PREREQUISITES:"
echo "  ✓ EC2 instance running (Amazon Linux/Ubuntu)"
echo "  ✓ Security Group allows ports 22, 80"
echo "  ✓ SSH key pair ready"
echo ""
echo "=============================================="
echo "  STEP 1: Copy Files to EC2"
echo "=============================================="
echo ""
echo "Run on YOUR LOCAL MACHINE:"
echo ""
echo "scp -i your-key.pem -r /path/to/AWS ec2-user@YOUR-EC2-IP:/tmp/aws-app"
echo ""
echo "=============================================="
echo "  STEP 2: SSH to EC2"
echo "=============================================="
echo ""
echo "ssh -i your-key.pem ec2-user@YOUR-EC2-IP"
echo ""
echo "=============================================="
echo "  STEP 3: Deploy Application"
echo "=============================================="
echo ""
echo "Run on EC2:"
echo ""
echo "sudo cp -r /tmp/aws-app /opt/aws-learning-platform"
echo "cd /opt/aws-learning-platform"
echo "sudo bash deploy_to_ec2.sh"
echo ""
echo "=============================================="
echo "  STEP 4: Access Your App"
echo "=============================================="
echo ""
echo "Open browser to: http://YOUR-EC2-IP"
echo ""
echo "To find your IP on EC2, run:"
echo "curl http://169.254.169.254/latest/meta-data/public-ipv4"
echo ""
echo "=============================================="
echo "  VERIFICATION"
echo "=============================================="
echo ""
echo "After deployment, verify with:"
echo "./check_status.sh"
echo ""
echo "View logs:"
echo "sudo journalctl -u aws-learning-platform -f"
echo ""
echo "=============================================="
echo ""
echo "📚 Full documentation in EC2_DEPLOYMENT.md"
echo "🎨 Design details in DEPLOYMENT_README.md"
echo "✅ Setup checklist in SETUP_COMPLETE.md"
echo ""
echo "=============================================="
